#spring:
#cloud:
#  gateway:
#    globalcors:
#      cors-configurations:
#        '[/**]':
#          allowedOrigins: "http://localhost:3000/**"
#          allowedMethods:
#            - GET
#            - POST
#            - OPTIONS
#            - OPTION
#            - PUT
#            - DELETE
#          add-to-simple-url-handler-mapping: true
