version: '4'
networks:
  backend-network:
    driver: bridge
    name: backend-network

services:
  configserver:
    image: sw_image-configserver:1
    ports:
      - "8888:8888"
    networks:
      - backend-network

  # safewalletiam:
  #   image: sw_image-safewallet:1
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - backend-network
  #   depends_on:
  #     - configserver

  eurekaserver:
    image: sw_image-server:1
    ports:
      - "8761:8761"
    networks:
      - backend-network
  gateway:
    image: sw_image-gateway:1
    ports:
      - "9090:9090"
    networks:
      - backend-network

  exportpdf:
    image: sw_image-exportpdf:1
    ports:
      - "8085:8082"
    networks:
      - backend-network

  keycloack:
    image: sw_image-keycloack:1
    ports:
      - "8081:8081"
    networks:
      - backend-network

  userdatafull:
    image: sw_image-userfull:1
    ports:
      - "8087:8080"
    networks:
      - backend-network

  transfers:
    image: sw_image-transfers:1
    ports:
      - "8086:8086"
    networks:
      - backend-network
