version: '3.8'
networks:
  backend-network:
    driver: bridge
    name: backend-network

services:
  configserver:
    image: mcvetic97/sw-configserver:v1
    ports:
      - "8888:8888"
    networks:
      - backend-network

  safewalletiam:
    image: mcvetic97/safewalletiam:1
    ports:
    - "8080:8080"
    networks:
    - backend-network

  eurekaserver:
    image: mcvetic97/sw-server:v1
    ports:
      - "8761:8761"
    networks:
      - backend-network
  gateway:
    image: mcvetic97/sw-gateway:v1
    ports:
      - "9090:9090"
    networks:
      - backend-network

  exportpdf:
    image: mcvetic97/sw-exportpdf:v1
    ports:
      - "8085:8082"
    networks:
      - backend-network

  keycloack:
    image: sw_image-keycloack:1
    ports:
      - "8081:8081"
    networks:
      - backend-network

  userdatafull:
    image: mcvetic97/sw-userfull:v1
    ports:
      - "8087:8080"
    networks:
      - backend-network

  transfers:
    image: mcvetic97/sw-transfers:v1
    ports:
      - "8086:8086"
    networks:
      - backend-network
