version: '3.8'
networks:
  backend-network:
    driver: bridge
    name: backend-network

services:
  configserver:
    image: mcvetic97/sw-configserver:v1
    ports:
      - "8888:8888"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: '0.5' # Límite de CPU
          memory: 230M # Límite de memoria

  safewalletiam:
    image: mcvetic97/safewalletiam:1
    ports:
      - "8080:8080"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: '0.5' # Límite de CPU
          memory: 380M # Límite de memoria

  eurekaserver:
    image: mcvetic97/sw-server:v1
    ports:
      - "8761:8761"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: '0.5' # Límite de CPU
          memory: 280M # Límite de memoria

  gateway:
    image: mcvetic97/sw-gateway:v1
    ports:
      - "9090:9090"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: '0.5' # Límite de CPU
          memory: 300M # Límite de memoria

  exportpdf:
    image: mcvetic97/sw-exportpdf:v1
    ports:
      - "8085:8082"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: '0.5' # Límite de CPU
          memory: 230M # Límite de memoria

  keycloack:
    image: sw_image-keycloack:1
    ports:
      - "8081:8081"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: '0.5' # Límite de CPU
          memory: 320M # Límite de memoria

  userdatafull:
    image: mcvetic97/sw-userfull:v1
    ports:
      - "8087:8080"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: '0.5' # Límite de CPU
          memory: 400M # Límite de memoria

  transfers:
    image: mcvetic97/sw-transfers:v1
    ports:
      - "8086:8086"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: '1' # Límite de CPU
          memory: 400M # Límite de memoria
