server:
  port: 9090

spring:
  security:
    oauth2:
      client:
        provider:
          safewallet: # Nombre del reino
            issuer-uri: http://localhost:8080/realms/safewallet
        registration:
          safewallet: # Nombre del reino
            provider: safewallet # Nombre del reino
            scope: openid
            client-id: safewallet-gateway-client # Nombre del cliente
            client-secret: htvKb50Pw8h190Gp9vkY2ZXoJNyn1tTo # Secret
            authorization-grant-type: authorization_code






  config:
    enabled: false

logging:
  level:
    org.springframework.security: DEBUG

cloud:
  config:
    enabled: false
