spring:
  cloud:
    gateway:
      routes:
        - id: register-full
          uri: lb://REGISTER-FULL
          predicates:
            - Path=/user/**

        - id: register-keycloak
          uri: lb://REGISTER-KEYCLOAK
          predicates:
            - Path=/userKeycloak/**


      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
